/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package presentacion;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author jcarlosad7
 */
public class FrmPrincipal extends javax.swing.JFrame {

    private final String tipoUsuario;
    
    public FrmPrincipal(String tipoUsuario) {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        setTitle("Sistema");
        this.tipoUsuario = tipoUsuario;
        this.cargarOpcionesMenu();       
    }

    private void cargarOpcionesMenu(){
       if ("administrador".equals(tipoUsuario)) {
            // Permitir acceso completo a todas las opciones de menú
            menuAlmacen.setEnabled(true);
            jMenu1.setEnabled(true);
            menuPermisos.setEnabled(true);
            
        } else if ("colaborador".equals(tipoUsuario)) {
            // Bloquear acceso a ciertas opciones de menú para colaboradores
            menuAlmacen.setEnabled(false);
            //jMenu1.setEnabled(false);
            itemUsuario.setEnabled(false);
            itemEmpleado.setEnabled(true);
            menuPermisos.setEnabled(true); // Bloquear todo el menú de Ventas
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane(){
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.setColor(Color.white);
                g.fillRect(0, 0, getWidth(), getHeight());
            }

        };
        menuBar = new javax.swing.JMenuBar();
        menuAlmacen = new javax.swing.JMenu();
        itemCargos = new javax.swing.JMenuItem();
        itemAreas = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        itemUsuario = new javax.swing.JMenuItem();
        itemEmpleado = new javax.swing.JMenuItem();
        menuPermisos = new javax.swing.JMenu();
        itemPermisos = new javax.swing.JMenuItem();
        itemAsistencias = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBackground(new java.awt.Color(255, 255, 255));

        menuAlmacen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/images/categoria.png"))); // NOI18N
        menuAlmacen.setText("Cargos");
        menuAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAlmacenActionPerformed(evt);
            }
        });

        itemCargos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemCargos.setText("Cargos");
        itemCargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCargosActionPerformed(evt);
            }
        });
        menuAlmacen.add(itemCargos);

        itemAreas.setText("Areas");
        itemAreas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAreasActionPerformed(evt);
            }
        });
        menuAlmacen.add(itemAreas);

        menuBar.add(menuAlmacen);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/images/User.png"))); // NOI18N
        jMenu1.setText("Seguridad");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        itemUsuario.setText("Usuarios");
        itemUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(itemUsuario);

        itemEmpleado.setText("Empleados");
        itemEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEmpleadoActionPerformed(evt);
            }
        });
        jMenu1.add(itemEmpleado);

        menuBar.add(jMenu1);

        menuPermisos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/images/permiso.png"))); // NOI18N
        menuPermisos.setText("Permisos");
        menuPermisos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPermisosActionPerformed(evt);
            }
        });

        itemPermisos.setText("Permisos");
        itemPermisos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPermisosActionPerformed(evt);
            }
        });
        menuPermisos.add(itemPermisos);

        itemAsistencias.setText("Asistencias");
        itemAsistencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAsistenciasActionPerformed(evt);
            }
        });
        menuPermisos.add(itemAsistencias);

        menuBar.add(menuPermisos);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemCargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCargosActionPerformed
        FrmCargo frm = new FrmCargo();
        desktopPane.add(frm);
        frm.toFront();
        frm.setVisible(true);
    }//GEN-LAST:event_itemCargosActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        FrmEmpleado frm = new FrmEmpleado();
        desktopPane.add(frm);
        frm.toFront();
        frm.setVisible(true);
        
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void itemUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemUsuarioActionPerformed
        FrmUsuario frm = new FrmUsuario();
        desktopPane.add(frm);
        frm.toFront();
        frm.setVisible(true);
    }//GEN-LAST:event_itemUsuarioActionPerformed

    private void menuPermisosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPermisosActionPerformed
        
    }//GEN-LAST:event_menuPermisosActionPerformed

    private void menuAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAlmacenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuAlmacenActionPerformed

    private void itemAreasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAreasActionPerformed
        FrmArea frm = new FrmArea();
        desktopPane.add(frm);
        frm.toFront();
        frm.setVisible(true);
    }//GEN-LAST:event_itemAreasActionPerformed

    private void itemEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEmpleadoActionPerformed
        FrmEmpleado frm = new FrmEmpleado();
        desktopPane.add(frm);
        frm.toFront();
        frm.setVisible(true);
    }//GEN-LAST:event_itemEmpleadoActionPerformed

    private void itemPermisosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPermisosActionPerformed
        FrmPermiso frm = new FrmPermiso();
        desktopPane.add(frm);
        frm.toFront();
        frm.setVisible(true);
    }//GEN-LAST:event_itemPermisosActionPerformed

    private void itemAsistenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAsistenciasActionPerformed
        FrmAsistencia frm = new FrmAsistencia();
        desktopPane.add(frm);
        frm.toFront();
        frm.setVisible(true);
    }//GEN-LAST:event_itemAsistenciasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem itemAreas;
    private javax.swing.JMenuItem itemAsistencias;
    private javax.swing.JMenuItem itemCargos;
    private javax.swing.JMenuItem itemEmpleado;
    private javax.swing.JMenuItem itemPermisos;
    private javax.swing.JMenuItem itemUsuario;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu menuAlmacen;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuPermisos;
    // End of variables declaration//GEN-END:variables

}
